name: Publish package to Github Packages
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jannis2301'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Test
        run: npm test

      - run: |
          echo @jannis2301:https://npm.pkg.github.com/ > dist/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> dist/.npmrc

      - run: npm ci

      - run: npm publish
        working-directory: ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
